version: '3.4'

services:
  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=basketdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_basketdb:/var/lib/postgresql/data/
  
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "5341:5341"
      - "9091:80"
